import { Coffee } from './models'

export const storeCoffeeList: Coffee[] = [
  {
    id: 1,
    name: 'Expresso Tradicional',
    type: 'expresso',
    categories: ['Tradicional'],
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 9.9,
    inventoryAmount: 99,
  },
  {
    id: 2,
    name: 'Expresso Americano',
    type: 'expresso_americano',
    categories: ['Tradicional'],
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 8.9,
    inventoryAmount: 99,
  },
  {
    id: 3,
    name: 'Expresso Cremoso',
    type: 'expresso_cremoso',
    categories: ['Tradicional'],
    description: 'Café expresso tradicional com espuma cremosa',
    price: 10.9,
    inventoryAmount: 99,
  },
  {
    id: 4,
    name: 'Expresso Gelado',
    type: 'gelado',
    categories: ['Tradicional', 'Gelado'],
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 9.9,
    inventoryAmount: 99,
  },
  {
    id: 5,
    name: 'Café com Leite',
    type: 'com_leite',
    categories: ['Tradicional', 'Com leite'],
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 12.9,
    inventoryAmount: 99,
  },
  {
    id: 6,
    name: 'Latte',
    type: 'latte',
    categories: ['Tradicional', 'Com leite'],
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 13.9,
    inventoryAmount: 99,
  },
  {
    id: 7,
    name: 'Cappuccino',
    type: 'cappuccino',
    categories: ['Tradicional', 'Com leite'],
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 11.9,
    inventoryAmount: 99,
  },
  {
    id: 8,
    name: 'Macchiato',
    type: 'macchiato',
    categories: ['Tradicional', 'Com leite'],
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 10.9,
    inventoryAmount: 99,
  },
  {
    id: 9,
    name: 'Mochaccino',
    type: 'mochaccino',
    categories: ['Tradicional', 'Chocolate'],
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 9.9,
    inventoryAmount: 99,
  },
  {
    id: 10,
    name: 'Chocolate Quente',
    type: 'chocolate_quente',
    categories: ['Especial', 'Chocolate'],
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 13.9,
    inventoryAmount: 99,
  },
  {
    id: 11,
    name: 'Cubano',
    type: 'cubano',
    categories: ['Especial', 'Alcoólico', 'Gelado'],
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 16.9,
    inventoryAmount: 99,
  },
  {
    id: 12,
    name: 'Havaiano',
    type: 'Havaiano',
    categories: ['Especial'],
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 14.9,
    inventoryAmount: 99,
  },
  {
    id: 13,
    name: 'Árabe',
    type: 'arabe',
    categories: ['Especial'],
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 17.9,
    inventoryAmount: 99,
  },
  {
    id: 14,
    name: 'Irlandês',
    type: 'irlandes',
    categories: ['Especial', 'Alcoólico'],
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 21.9,
    inventoryAmount: 99,
  },
]
